version: "3"
services:
  optim-server:
    build:
      context: ""
      dockerfile: Dockerfile.optim-server
    image: optim-server:latest
    entrypoint:
      - /bin/entrypoint.sh
    env_file:
      - optim.env
    ports:
      - "6006"
  optim-nginx:
    build:
      context: ""
      dockerfile: Dockerfile.optim-nginx
    image: optim-nginx:latest
    env_file:
      - optim.env
    ports:
      - '80:80'
      - '443:443'
    links:
      - optim-server
    restart: always
  optim-scheduler:
    build:
      context: ""
      dockerfile: Dockerfile.optim-scheduler
    image: optim-scheduler:latest
    entrypoint:
      - /bin/entrypoint.sh
    env_file:
      - optim.env
    ports:
      - "6008"



