version: "3"
services:
  optim:
    image: 117859797117.dkr.ecr.us-east-1.amazonaws.com/binaize-optim-repo:latest
    logging:
      driver: awslogs
      options:
        awslogs-group: binaize-optimize
        awslogs-region: us-east-1
        awslogs-stream-prefix: optim
    entrypoint:
      - /bin/entrypoint.sh
    env_file:
      - optim.env
    environment:
      - SERVICE_PORT=6006
      - SERVICE_TIMEOUT=900
      - WORKER_COUNT=2
    ports:
      - "6006"
  nginx:
    image: nginx:latest
    depends_on:
      - optim
    ports:
      - "443:443"