version: "3"
services:
  optim-test:
    build:
      context: ""
      dockerfile: Dockerfile.optim-test
    image: optim-test:latest
    network_mode: bridge
    entrypoint:
      - /bin/test_suites.sh
    env_file:
      - optim-test.env