version: "3"
services:
  optim:
    build:
      context: ""
      dockerfile: Dockerfile.optim
    image: optim:latest
    entrypoint:
      - /bin/entrypoint.sh
    env_file:
      - ./config.env
    environment:
      - SERVICE_PORT=6006
      - SERVICE_TIMEOUT=900
      - WORKER_COUNT=2
    ports:
      - "6006"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs
    depends_on:
      - optim
    ports:
      - "80:80"
      - "443:443"



