version: "3"
services:
  optim:
    build:
      context: ""
      dockerfile: Dockerfile.optim
    image: optim:latest
    entrypoint:
      - /bin/entrypoint.sh
    env_file:
      - ./config.env
    ports:
      - "6006"
  nginx:
    build:
      context: ""
      dockerfile: Dockerfile.nginx
    env_file:
      - ./config.env
    ports:
      - '80:80'
      - '443:443'
    links:
      - optim
    restart: always



